## Q1. String Parsing Challenge

* You are given a string:
      - s = "id:101|name:Alice|dept:IT|salary:60000"

* Write Python code to convert it into a dictionary:
    - {"id": 101, "name": "Alice", "dept": "IT", "salary": 60000}

In [302]:
s = "id:101|name:Alice|dept:IT|salary:60000"

In [303]:
pairs = s.split('|')
pairs

['id:101', 'name:Alice', 'dept:IT', 'salary:60000']

In [304]:
res = {}
for i in pairs:
    k, v = i.split(':')
    if v.isdigit():
        v = int(v)
    res[k] = v

print(res)

{'id': 101, 'name': 'Alice', 'dept': 'IT', 'salary': 60000}

## Q2. List Flattening

* Given a nested list:
    - lst = [[1, 2], [3, 4, [5, 6]], 7, [8, [9, 10]]]

* Write a function to flatten it into a single list →
    - [1,2,3,4,5,6,7,8,9,10] (no recursion allowed).

In [306]:
lst = [[1, 2], [3, 4, [5, 6]], 7, [8, [9, 10]]]

def flatten_list(l):
    result = []
    for i in l:
        if isinstance(i, list):
            result.extend(flatten_list(i))
        else:
            result.append(i)
    return result
    
print(flatten_list(lst))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## Q3. Frequency Counter

* Write Python code to find the top 3 most common words in the following list using collections.Counter:

- words = ["apple", "banana", "apple", "orange", "banana", "apple", "kiwi", "kiwi"]

In [308]:
from collections import Counter

words = ["apple", "banana", "apple", "orange", "banana", "apple", "kiwi", "kiwi"]
freq = Counter(words)

print(freq.most_common(3))

[('apple', 3), ('banana', 2), ('kiwi', 2)]

## Q4. DataFrame Row Filtering (Lambda + Apply)

From the dataset:

In [310]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [25, 30, 35, 40, 45],
    "Salary": [50000, 60000, 55000, 65000, 70000]
}
df = pd.DataFrame(data)

### Filter out rows where Salary > (Age × 1800).

In [312]:
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   55000
3    David   40   65000
4      Eva   45   70000

In [313]:
df[df['Salary'] > (df["Age"]*1800)]

    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   60000

## Q5. Groupby Transformation

* Using the same df, add a new column "Relative_Salary" where each salary is divided by the average salary of that employee’s age group bucket (20-30, 30-40, 40-50).

In [315]:
bins = [20, 30, 40, 50]
labels = ['20-30', '30-40', '40-50']

df['age_grp'] = pd.cut(df['Age'], bins = bins, labels = labels)

In [316]:
df['avg_sal_bt'] = df.groupby('age_grp')['Salary'].transform('mean')

C:\Users\Admin\AppData\Local\Temp\ipykernel_8204\892802511.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['avg_sal_bt'] = df.groupby('age_grp')['Salary'].transform('mean')

In [317]:
df['Relative_Salary'] = df['Salary'] / df['avg_sal_bt']
df

      Name  Age  Salary age_grp  avg_sal_bt  Relative_Salary
0    Alice   25   50000   20-30     55000.0         0.909091
1      Bob   30   60000   20-30     55000.0         1.090909
2  Charlie   35   55000   30-40     60000.0         0.916667
3    David   40   65000   30-40     60000.0         1.083333
4      Eva   45   70000   40-50     70000.0         1.000000

## Q6. Numpy Challenge – Matrix Operations

* Create a 3×3 matrix with numbers 1–9 using NumPy.

* Find its determinant.

In [319]:
import numpy as np

In [320]:
arr = np.random.randint(1, 9, size = (3,3))
arr

array([[6, 2, 7],
       [4, 5, 3],
       [4, 2, 6]])

In [321]:
np.linalg.det(arr)

36.000000000000014

## Q7. Regex Filtering

* Given a list of emails:
    - emails = ["alice@gmail.com", "bob@yahoo.com", "charlie@company.org", "david@gmail.com"]
Extract only Gmail addresses using regex.

In [323]:
emails = ["alice@gmail.com", "bob@yahoo.com", "charlie@company.org", "david@gmail.com"]

In [324]:
import re

gmail = [i for i in emails if re.findall(r'@gmail\.com', i)]
print(gmail)

['alice@gmail.com', 'david@gmail.com']

## Q8. OOP + Data Handling

* Create a Python class Employee with attributes name, department, salary.

* Add a method to increase salary by 10%.

* Create objects for 3 employees and apply the raise.

In [326]:
class Employee:
    def __init__(self, name, department, salary):
        self.name = name
        self.department = department
        self.salary = salary

    def sal_inc(self):
        updated_sal = self.salary + (self.salary*0.1)
        print(f"Updated salary for {self.name} is: {updated_sal}")

p1 = Employee('Alice', 'HR', 30000)
p1.sal_inc()

p2 = Employee('Bob', 'IT', 50000)
p2.sal_inc()

p3 = Employee('Charlie', 'Finance', 20000)
p3.sal_inc()

Updated salary for Alice is: 33000.0
Updated salary for Bob is: 55000.0
Updated salary for Charlie is: 22000.0

## Q9. Dictionary Challenge

* You have a dictionary:
    - sales = {"apple": 50, "banana": 30, "orange": 40, "mango": 60}


* Sort it by values in descending order and return the top 2 fruits with highest sales.

In [328]:
sales = {"apple": 50, "banana": 30, "orange": 40, "mango": 60}

top_2 = dict(Counter(sales).most_common(2))
top_2

{'mango': 60, 'apple': 50}

## Q10 (Revised): Set & String Challenge

* You are given two strings:

- s1 = "datascience"
- s2 = "statistics"


* Task:

* Find the common characters between the two strings.

* Find the characters that are unique to each string.

* Return results as sets.

* Expected Output Example:

- Common: {'s', 't', 'a', 'c', 'i'}
- Unique to s1: {'d', 'e', 'n'}
- Unique to s2: {'o'}

In [330]:
    s1 = "datascience"
    s2 = "statistics"
    
    set1 = set(s1)
    set2 = set(s2)
    
    common = set1 & set2
    
    unique1 = set1-set2
    unique2 = set2-set1
    
    print("Common:", common)
    print("Unique to s1:", unique1)
    print("Unique to s2:", unique2)

Common: {'i', 's', 'c', 't', 'a'}
Unique to s1: {'e', 'd', 'n'}
Unique to s2: set()